services:
  veopromptgenerator:
    image: veopromptgenerator-dev
    user: '${UID:-1000}:${GID:-1000}'
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: 'true'
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app:z
      - /usr/src/app/node_modules
    command: ['npm', 'run', 'dev', '--', '--host', '0.0.0.0', '--port', '8080']
