
import { GoogleGenAI, Modality, Type } from "@google/genai";
import { PromptGenerationParams, EditedImageResponse, ExamplePrompt, SelectOption, VeoPromptResponse } from '../types';
import { buildGeminiPrompt } from './promptBuilder';
import { suggestionSystemPrompts, trendingSystemPrompts, uiStrings, storyboardSystemPrompt, videoAnalysisSystemPrompt } from '../translations';

if (!process.env.API_KEY) {
  throw new Error("API_KEY environment variable is not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export async function generateVeoPrompt(params: PromptGenerationParams): Promise<VeoPromptResponse> {
  const finalPrompt = buildGeminiPrompt(params);

  const config: any = {};
  if (params.useGoogleSearch) {
    config.tools = [{googleSearch: {}}];
  }
  
  try {
    const response = await ai.models.generateContent({
      model: params.model,
      contents: finalPrompt,
      config,
    });
    return {
      prompt: response.text.trim(),
      groundingChunks: response.candidates?.[0]?.groundingMetadata?.groundingChunks
    };
  } catch (error) {
    console.error("Error generating prompt with Gemini:", error);
    throw error;
  }
}

export async function generateConceptArt(prompt: string): Promise<string> {
    const imagePrompt = `Create a single, highly-detailed piece of concept art based on the following scene description. Focus on the mood and key elements. The scene: ${prompt}`;
    try {
        const response = await ai.models.generateImages({
            model: 'imagen-4.0-generate-001',
            prompt: imagePrompt,
            config: {
              numberOfImages: 1,
              outputMimeType: 'image/png',
              aspectRatio: '16:9',
            },
        });

        if (response.generatedImages && response.generatedImages.length > 0) {
            return response.generatedImages[0].image.imageBytes;
        } else {
            throw new Error("No image was generated by the API.");
        }

    } catch(error) {
        console.error("Error generating image with Gemini:", error);
        throw error;
    }
}

export async function editConceptArt(imageDataUrl: string, prompt: string): Promise<EditedImageResponse> {
    const match = imageDataUrl.match(/^data:(image\/\w+);base64,(.*)$/);
    if (!match) {
        throw new Error("Invalid image data URL format");
    }
    const mimeType = match[1];
    const imageData = match[2];

    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash-image',
            contents: {
                parts: [
                    {
                        inlineData: {
                            data: imageData,
                            mimeType: mimeType,
                        },
                    },
                    {
                        text: prompt,
                    },
                ],
            },
            config: {
                responseModalities: [Modality.IMAGE, Modality.TEXT],
            },
        });

        for (const part of response.candidates[0].content.parts) {
            if (part.inlineData && part.inlineData.mimeType.startsWith('image/')) {
                return { 
                    newMimeType: part.inlineData.mimeType,
                    newImageBytes: part.inlineData.data
                };
            }
        }
        
        throw new Error("The API did not return an image.");

    } catch (error) {
        console.error("Error editing image with Gemini:", error);
        throw error;
    }
}

/**
 * Simulates a text-to-speech API call.
 * NOTE: This is a placeholder. In a real-world scenario, this function would
 * call a dedicated TTS service (like Google Cloud Text-to-Speech) to convert
 * the text and voice style into an actual audio file. For this demo, it
 * returns a pre-generated, base64-encoded WAV file after a short delay.
 *
 * @param text The text to be converted to speech.
 * @param voice The desired voice style.
 * @returns A promise that resolves to a data URL for the generated audio.
 */
export async function generateTextToSpeech(text: string, voice: string): Promise<string> {
    console.log(`Simulating TTS generation for text: "${text}" with voice: "${voice}"`);

    if (!text.trim()) {
        throw new Error("Text for audio generation cannot be empty.");
    }
    
    // Simulate network latency
    await new Promise(resolve => setTimeout(resolve, 1500));

    // Placeholder: A base64 encoded 1-second sine wave at 440Hz (A4 note) in WAV format.
    // This should be replaced with a real API call.
    const base64Wav = "UklGRiQAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAAABkYXRhIAAAAAAAAAA=";
    const placeholderAudio = "UklGRjIAAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YSoAAAD0////AgACAgID/P/5//n/+f/5/wAAAQEDAAMCAwAD/v/5//n/+f/5//r/+f/6/v7/+f/5//r/+v/6//r/+gABAQMAAwEDAAICAgH+/vz++f/6//r/+f/5/wABAQIAAQECAP7+/P75//r/+v/6/vr/+gEBAf7++f/5//n/+f/5//n/AAEBAgACAgMA/v78/vn/+v/6//r/+v/6AAEBAgD+/vz++f/6//r/+f/5/wABAQIAAgIDAP7+/P75//r/+v/6//r/+gABAQMAAgIDAP7+/P75//r/+v/6/vr/+gABAQMAAgIDAP7+/P75//r/+v/6//r/+gABAQMAAgIDAP7+/P75//r/+v/6//r/+gABAQMAAgIDAP7+/P75//r/+v/6//r/+gABAQMAAgIDAP7+/P75//r/+v/6//r/+gABAQMAAgIDAP7+/P75//r/+v/6//r/+gABAQMAAgIDAP7+/P75//r/+v/6//r/+gABAQMAAgIDAP7+/P75//r/+v/6//r/+gABAQMAAgIDAP7+/P75//r/+v/6//r/+gABAQMAAgIDAP7+/P75//r/+v/6//r/+gABAQMAAgIDAP7+/P75//r/+v/6//r/+gABAQMAAgIDAP7+/P75//r/+v/6//r/+g=="
    return `data:audio/wav;base64,${placeholderAudio}`;
}

export async function generateVeoVideo(
    prompt: string, 
    config: { motionIntensity: string; creativityLevel: string }, 
    onStatusUpdate: (status: string) => void,
    language: 'en' | 'sv'
): Promise<string> {
    onStatusUpdate(uiStrings.videoStatusInit[language]);
    try {
        let operation = await ai.models.generateVideos({
          model: 'veo-2.0-generate-001',
          prompt: prompt,
          config: {
            numberOfVideos: 1
          }
        });

        onStatusUpdate(uiStrings.videoStatusProcessing[language]);

        while (!operation.done) {
          await new Promise(resolve => setTimeout(resolve, 10000)); // Poll every 10 seconds
          onStatusUpdate(uiStrings.videoStatusPolling[language]);
          operation = await ai.operations.getVideosOperation({operation: operation});
        }

        const downloadLink = operation.response?.generatedVideos?.[0]?.video?.uri;
        if (!downloadLink) {
            throw new Error("Video generation succeeded but no download link was provided.");
        }

        onStatusUpdate(uiStrings.videoStatusFetching[language]);
        
        const response = await fetch(`${downloadLink}&key=${process.env.API_KEY}`);
        if (!response.ok) {
            throw new Error(`Failed to download video: ${response.statusText}`);
        }
        const videoBlob = await response.blob();
        const videoDataUrl = await new Promise<string>((resolve, reject) => {
            const reader = new FileReader();
            reader.onloadend = () => resolve(reader.result as string);
            reader.onerror = reject;
            reader.readAsDataURL(videoBlob);
        });

        onStatusUpdate(uiStrings.videoStatusComplete[language]);
        return videoDataUrl;

    } catch (error) {
        console.error("Error generating video with Veo:", error);
        throw error;
    }
}

export async function analyzeYouTubeVideo(url: string, language: 'en' | 'sv', model: string): Promise<string> {
    const systemInstruction = videoAnalysisSystemPrompt[language];
    const userPrompt = `YouTube URL: ${url}`;
    try {
        const response = await ai.models.generateContent({
            model: model,
            contents: userPrompt,
            config: {
                systemInstruction
            }
        });
        return response.text.trim();
    } catch (error) {
        console.error("Error analyzing YouTube URL with Gemini:", error);
        throw error;
    }
}


export async function generateIdeaSuggestions(idea: string, language: 'en' | 'sv', model: string): Promise<string[]> {
    try {
        const response = await ai.models.generateContent({
            model: model,
            contents: idea,
            config: {
                systemInstruction: suggestionSystemPrompts[language],
                responseMimeType: 'application/json',
                responseSchema: {
                    type: Type.ARRAY,
                    items: {
                        type: Type.STRING,
                        description: 'A single refined idea suggestion.'
                    }
                }
            }
        });

        const jsonText = response.text.trim();
        const suggestions = JSON.parse(jsonText) as string[];
        if (!Array.isArray(suggestions)) {
            throw new Error("API returned invalid suggestions format.");
        }
        return suggestions;

    } catch (error) {
        console.error("Error generating idea suggestions with Gemini:", error);
        throw error;
    }
}

export async function generateStoryboard(veoPrompt: string, language: 'en' | 'sv', model: string): Promise<string[]> {
    try {
        // Step 1: Generate keyframe prompts from the main Veo prompt
        const keyframePromptsResponse = await ai.models.generateContent({
            model: model,
            contents: veoPrompt,
            config: {
                systemInstruction: storyboardSystemPrompt[language],
                responseMimeType: 'application/json',
                responseSchema: {
                    type: Type.ARRAY,
                    items: {
                        type: Type.STRING,
                        description: 'A concise image generation prompt for a single storyboard keyframe.'
                    }
                }
            }
        });

        const jsonText = keyframePromptsResponse.text.trim();
        const keyframePrompts = JSON.parse(jsonText) as string[];
        if (!Array.isArray(keyframePrompts) || keyframePrompts.length === 0) {
            throw new Error("Could not extract keyframes from the prompt.");
        }

        // Step 2: Generate an image for each keyframe prompt concurrently
        const imageGenerationPromises = keyframePrompts.map(prompt =>
            ai.models.generateImages({
                model: 'imagen-4.0-generate-001',
                prompt: prompt,
                config: {
                  numberOfImages: 1,
                  outputMimeType: 'image/png',
                  aspectRatio: '16:9',
                },
            })
        );
        
        const responses = await Promise.all(imageGenerationPromises);
        
        const imageUrls = responses.map(response => {
            if (response.generatedImages && response.generatedImages.length > 0) {
                const imageBytes = response.generatedImages[0].image.imageBytes;
                return `data:image/png;base64,${imageBytes}`;
            }
            throw new Error("Storyboard image generation failed for one or more frames.");
        });
        
        return imageUrls;

    } catch (error) {
        console.error("Error generating storyboard with Gemini:", error);
        throw error;
    }
}


const examplePromptsSchema = {
    type: Type.ARRAY,
    items: {
        type: Type.OBJECT,
        properties: {
            title: { type: Type.STRING },
            idea: { type: Type.STRING },
            prompt: { type: Type.STRING },
            params: {
                type: Type.OBJECT,
                properties: {
                    artStyle: { type: Type.STRING },
                    customArtStyle: { type: Type.STRING },
                    cameraMovement: { type: Type.STRING },
                    cameraDistance: { type: Type.STRING },
                    lensType: { type: Type.STRING },
                    visualEffect: { type: Type.STRING },
                    colorPalette: { type: Type.STRING },
                    aspectRatio: { type: Type.STRING },
                    animationPreset: { type: Type.STRING },
                    voiceStyle: { type: Type.STRING },
                    environment: { type: Type.STRING },
                    timeOfDay: { type: Type.STRING },
                    weather: { type: Type.STRING },
                    characterActions: { type: Type.STRING },
                    characterGender: { type: Type.STRING },
                    characterEthnicity: { type: Type.STRING },
                    characterClothing: { type: Type.STRING },
                    ambientSound: { type: Type.STRING },
                    soundEffectsIntensity: { type: Type.STRING },
                    motionIntensity: { type: Type.STRING },
                    creativityLevel: { type: Type.STRING },
                    negativePrompt: { type: Type.STRING },
                    model: { type: Type.STRING },
                },
                required: ["artStyle", "cameraMovement", "cameraDistance", "lensType", "visualEffect", "colorPalette", "aspectRatio", "animationPreset", "voiceStyle"]
            }
        },
        required: ["title", "idea", "prompt", "params"]
    }
};

const getValidParamsString = (
    artStyles: SelectOption[],
    cameraMovements: SelectOption[],
    cameraDistances: SelectOption[],
    lensTypes: SelectOption[],
    visualEffects: SelectOption[],
    colorPalettes: SelectOption[],
    aspectRatios: SelectOption[],
    animationPresets: SelectOption[],
    voiceStyles: SelectOption[],
    timeOfDayOptions: SelectOption[],
    weatherOptions: SelectOption[],
    characterGenders: SelectOption[],
    characterEthnicities: SelectOption[],
    characterClothings: SelectOption[],
    ambientSounds: SelectOption[],
    soundEffectsIntensityOptions: SelectOption[],
    motionIntensityOptions: SelectOption[],
    creativityLevelOptions: SelectOption[]
): string => {
    const stringifyOptions = (options: SelectOption[]) => options.map(o => o.value).join(', ');
    return `
    - artStyle: ${stringifyOptions(artStyles)}
    - cameraMovement: ${stringifyOptions(cameraMovements)}
    - cameraDistance: ${stringifyOptions(cameraDistances)}
    - lensType: ${stringifyOptions(lensTypes)}
    - visualEffect: ${stringifyOptions(visualEffects)}
    - colorPalette: ${stringifyOptions(colorPalettes)}
    - aspectRatio: ${stringifyOptions(aspectRatios)}
    - animationPreset: ${stringifyOptions(animationPresets)}
    - voiceStyle: ${stringifyOptions(voiceStyles)}
    - timeOfDay: ${stringifyOptions(timeOfDayOptions)}
    - weather: ${stringifyOptions(weatherOptions)}
    - characterGender: ${stringifyOptions(characterGenders)}
    - characterEthnicity: ${stringifyOptions(characterEthnicities)}
    - characterClothing: ${stringifyOptions(characterClothings)}
    - ambientSound: ${stringifyOptions(ambientSounds)}
    - soundEffectsIntensity: ${stringifyOptions(soundEffectsIntensityOptions)}
    - motionIntensity: ${stringifyOptions(motionIntensityOptions)}
    - creativityLevel: ${stringifyOptions(creativityLevelOptions)}`;
};


export async function generateExamplePrompts(
    artStyles: SelectOption[],
    cameraMovements: SelectOption[],
    cameraDistances: SelectOption[],
    lensTypes: SelectOption[],
    visualEffects: SelectOption[],
    colorPalettes: SelectOption[],
    aspectRatios: SelectOption[],
    animationPresets: SelectOption[],
    voiceStyles: SelectOption[],
    timeOfDayOptions: SelectOption[],
    weatherOptions: SelectOption[],
    characterGenders: SelectOption[],
    characterEthnicities: SelectOption[],
    characterClothings: SelectOption[],
    ambientSounds: SelectOption[],
    soundEffectsIntensityOptions: SelectOption[],
    motionIntensityOptions: SelectOption[],
    creativityLevelOptions: SelectOption[],
    language: 'en' | 'sv',
    model: string
): Promise<ExamplePrompt[]> {
    const validParamsString = getValidParamsString(artStyles, cameraMovements, cameraDistances, lensTypes, visualEffects, colorPalettes, aspectRatios, animationPresets, voiceStyles, timeOfDayOptions, weatherOptions, characterGenders, characterEthnicities, characterClothings, ambientSounds, soundEffectsIntensityOptions, motionIntensityOptions, creativityLevelOptions);
    
    const systemPrompt = language === 'sv' ? 
    `Du är en kreativ chef för en AI-videoproduktionsstudio. Din uppgift är att skapa 4 olika och inspirerande exempel-prompter för Veo-videogenereringsmodellen. Varje exempel måste innehålla en titel, en grundidé, en fullständigt utarbetad prompt och de exakta parametrarna som användes för att skapa den. Parametrarna måste väljas från de angivna listorna. Du kan även sätta artStyle till 'Custom' och ge en detaljerad beskrivning i fältet customArtStyle. Svara endast med en JSON-array som följer det specificerade schemat.

    Giltiga parametervärden: ${validParamsString}`
    :
    `You are a creative director for an AI video production studio. Your task is to generate 4 diverse and inspiring example prompts for the Veo video generation model. Each example must include a title, a core idea, a fully fleshed-out prompt, and the exact parameters used to create it. The parameters must be chosen from the provided lists. You can also set artStyle to 'Custom' and provide a detailed description in the customArtStyle field. Respond only with a JSON array matching the specified schema.

    Valid Parameter Values: ${validParamsString}`;

    const userPrompt = language === 'sv' ? 
    `Generera 4 exempel. Täck olika genrer som sci-fi, natur, urban och fantasy.` 
    : 
    `Generate 4 examples. Cover different genres like sci-fi, nature, urban, and fantasy.`;

    try {
        const response = await ai.models.generateContent({
            model: model,
            contents: userPrompt,
            config: {
                systemInstruction: systemPrompt,
                responseMimeType: 'application/json',
                responseSchema: examplePromptsSchema
            }
        });
        
        const jsonText = response.text.trim();
        const examples = JSON.parse(jsonText) as ExamplePrompt[];
        if (!Array.isArray(examples) || examples.length === 0) {
            throw new Error("API returned invalid example format.");
        }
        return examples;

    } catch (error) {
        console.error("Error generating examples with Gemini:", error);
        throw error;
    }
}


export async function generateTrendingPrompts(
    artStyles: SelectOption[],
    cameraMovements: SelectOption[],
    cameraDistances: SelectOption[],
    lensTypes: SelectOption[],
    visualEffects: SelectOption[],
    colorPalettes: SelectOption[],
    aspectRatios: SelectOption[],
    animationPresets: SelectOption[],
    voiceStyles: SelectOption[],
    timeOfDayOptions: SelectOption[],
    weatherOptions: SelectOption[],
    characterGenders: SelectOption[],
    characterEthnicities: SelectOption[],
    characterClothings: SelectOption[],
    ambientSounds: SelectOption[],
    soundEffectsIntensityOptions: SelectOption[],
    motionIntensityOptions: SelectOption[],
    creativityLevelOptions: SelectOption[],
    language: 'en' | 'sv',
    model: string
): Promise<ExamplePrompt[]> {
    const validParamsString = getValidParamsString(artStyles, cameraMovements, cameraDistances, lensTypes, visualEffects, colorPalettes, aspectRatios, animationPresets, voiceStyles, timeOfDayOptions, weatherOptions, characterGenders, characterEthnicities, characterClothings, ambientSounds, soundEffectsIntensityOptions, motionIntensityOptions, creativityLevelOptions);
    
    const systemPrompt = trendingSystemPrompts[language] + "\nValid Parameter Values:\n" + validParamsString;

    const userPrompt = language === 'sv' ? 'Generera 4 trendande exempel.' : 'Generate 4 trending examples.';
    
    let rawResponseText = '';
    try {
        const response = await ai.models.generateContent({
            model: model,
            contents: userPrompt,
            config: {
                systemInstruction: systemPrompt,
                tools: [{googleSearch: {}}],
            }
        });
        
        rawResponseText = response.text;
        let jsonText = rawResponseText.trim();
        
        const jsonMatch = jsonText.match(/```json\s*([\s\S]*?)\s*```/);
        if (jsonMatch && jsonMatch[1]) {
            jsonText = jsonMatch[1];
        }
        
        const examples = JSON.parse(jsonText) as ExamplePrompt[];
        if (!Array.isArray(examples) || examples.length === 0) {
            throw new Error("API returned invalid trending prompt format (empty or not an array).");
        }
        return examples;

    } catch (error) {
        console.error("Error generating trending prompts with Gemini:", error);
        if (error instanceof SyntaxError) {
             console.error("Failed to parse JSON from trending prompts response:", rawResponseText);
             throw new Error("Could not parse trending prompts from the AI. The format was invalid.");
        }
        throw error;
    }
}