import type { CreatorRecipeV1 } from '@core/types/creatorDelivery';
export const CREATOR_RECIPES: readonly CreatorRecipeV1[] = [
  {
    schemaVersion: 1,
    id: 'quick-tip',
    category: 'social',
    titleKey: 'recipes.quick-tip.title',
    descriptionKey: 'recipes.quick-tip.description',
    aspectRatio: '9:16',
    sceneCount: 3,
    sceneIdeas: ['Hook: the problem', 'Show the useful technique', 'Result and invitation'],
    exampleId: 'social',
  },
  {
    schemaVersion: 1,
    id: 'product-story',
    category: 'social',
    titleKey: 'recipes.product-story.title',
    descriptionKey: 'recipes.product-story.description',
    aspectRatio: '9:16',
    sceneCount: 3,
    sceneIdeas: ['Product reveal', 'Detail in use', 'Benefit and invitation'],
  },
  {
    schemaVersion: 1,
    id: 'before-after',
    category: 'social',
    titleKey: 'recipes.before-after.title',
    descriptionKey: 'recipes.before-after.description',
    aspectRatio: '9:16',
    sceneCount: 3,
    sceneIdeas: ['Before state', 'The process', 'After state'],
  },
  {
    schemaVersion: 1,
    id: 'daily-moment',
    category: 'social',
    titleKey: 'recipes.daily-moment.title',
    descriptionKey: 'recipes.daily-moment.description',
    aspectRatio: '9:16',
    sceneCount: 3,
    sceneIdeas: ['Setting the scene', 'A human detail', 'A satisfying close'],
  },
  {
    schemaVersion: 1,
    id: 'mini-tutorial',
    category: 'social',
    titleKey: 'recipes.mini-tutorial.title',
    descriptionKey: 'recipes.mini-tutorial.description',
    aspectRatio: '9:16',
    sceneCount: 4,
    sceneIdeas: ['Outcome preview', 'First step', 'Second step', 'Final result'],
  },
  {
    schemaVersion: 1,
    id: 'announcement',
    category: 'social',
    titleKey: 'recipes.announcement.title',
    descriptionKey: 'recipes.announcement.description',
    aspectRatio: '1:1',
    sceneCount: 4,
    sceneIdeas: ['Attention grabber', 'What is new', 'Why it matters', 'Next step'],
  },
  {
    schemaVersion: 1,
    id: 'short-story',
    category: 'story',
    titleKey: 'recipes.short-story.title',
    descriptionKey: 'recipes.short-story.description',
    aspectRatio: '16:9',
    sceneCount: 4,
    sceneIdeas: ['The world', 'The challenge', 'The choice', 'The resolution'],
    exampleId: 'story',
  },
  {
    schemaVersion: 1,
    id: 'travel-diary',
    category: 'story',
    titleKey: 'recipes.travel-diary.title',
    descriptionKey: 'recipes.travel-diary.description',
    aspectRatio: '16:9',
    sceneCount: 4,
    sceneIdeas: ['Arrival', 'Place and detail', 'A personal moment', 'Departure'],
  },
  {
    schemaVersion: 1,
    id: 'documentary',
    category: 'story',
    titleKey: 'recipes.documentary.title',
    descriptionKey: 'recipes.documentary.description',
    aspectRatio: '16:9',
    sceneCount: 5,
    sceneIdeas: ['Question', 'Context', 'Evidence', 'Human perspective', 'Conclusion'],
  },
  {
    schemaVersion: 1,
    id: 'ambient-visual',
    category: 'music',
    titleKey: 'recipes.ambient-visual.title',
    descriptionKey: 'recipes.ambient-visual.description',
    aspectRatio: '16:9',
    sceneCount: 3,
    sceneIdeas: ['Soft opening', 'Flowing shapes', 'Quiet close'],
    exampleId: 'music',
  },
  {
    schemaVersion: 1,
    id: 'song-teaser',
    category: 'music',
    titleKey: 'recipes.song-teaser.title',
    descriptionKey: 'recipes.song-teaser.description',
    aspectRatio: '9:16',
    sceneCount: 3,
    sceneIdeas: ['Mood introduction', 'Hook imagery', 'Song title'],
  },
  {
    schemaVersion: 1,
    id: 'beat-loop',
    category: 'music',
    titleKey: 'recipes.beat-loop.title',
    descriptionKey: 'recipes.beat-loop.description',
    aspectRatio: '1:1',
    sceneCount: 4,
    sceneIdeas: ['Rhythm begins', 'Patterns build', 'Release', 'Loop return'],
  },
];
export const CREATOR_RECIPE_LABELS: Record<string, { title: string; description: string }> = {
  'quick-tip': { title: 'Quick tip', description: 'Teach one useful thing' },
  'product-story': { title: 'Product story', description: 'Show what makes your product useful' },
  'before-after': { title: 'Before / after', description: 'Show a transformation' },
  'daily-moment': { title: 'Daily moment', description: 'Share a small memorable moment' },
  'mini-tutorial': { title: 'Mini tutorial', description: 'Teach a process in four steps' },
  announcement: { title: 'Announcement', description: 'Introduce something new' },
  'short-story': { title: 'Short story', description: 'Tell a complete small story' },
  'travel-diary': { title: 'Travel diary', description: 'Capture a place and a feeling' },
  documentary: { title: 'Mini documentary', description: 'Explain a real subject' },
  'ambient-visual': {
    title: 'Ambient visual',
    description: 'Pair calm motion with instrumental audio',
  },
  'song-teaser': { title: 'Song teaser', description: 'Introduce a song and its mood' },
  'beat-loop': { title: 'Beat loop', description: 'Create a rhythmic visual sequence' },
};
